# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build -x test

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests with Gradle
        run: ./gradlew test

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Run integration tests with Gradle
        run: ./gradlew integrationTest

  check-coverage-verification:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Run jacoco test coverage verification with Gradle
        run: ./gradlew jacocoTestCoverageVerification
